import { TimelineConsts } from './timelineConsts';
import { TimelineStyle } from './styles/timelineStyle';
import { TimelineOptions } from './timelineOptions';
import { TimelineKeyframeStyle } from './styles/timelineKeyframeStyle';
import { TimelineRowStyle } from './styles/timelineRowStyle';
export declare const defaultTimelineStyle: TimelineStyle;
export declare const defaultTimelineKeyframeStyle: TimelineKeyframeStyle;
export declare const defaultTimelineRowStyle: TimelineRowStyle;
export declare const defaultTimelineOptions: TimelineOptions;
export declare const defaultTimelineConsts: TimelineConsts;
